package Pojo;
// Generated feb 18, 2016 6:40:59 p.m. by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer id;
     private Opcion opcion;
     private String descripcion;
     private Boolean gest;
     private Boolean gestProd;
     private Boolean gestPers;
     private Boolean gestCli;
     private Boolean venta;
     private Boolean ven;
     private Boolean conf;
     private Boolean confPerf;
     private Boolean confUsu;
     private Set usuarios = new HashSet(0);

    public Perfil() {
        this.opcion=new Opcion();
    }
	
    public Perfil(Opcion opcion) {
        this.opcion = opcion;
    }
    public Perfil(Opcion opcion, String descripcion, Boolean gest, Boolean gestProd, Boolean gestPers, Boolean gestCli, Boolean venta, Boolean ven, Boolean conf, Boolean confPerf, Boolean confUsu, Set usuarios) {
       this.opcion = opcion;
       this.descripcion = descripcion;
       this.gest = gest;
       this.gestProd = gestProd;
       this.gestPers = gestPers;
       this.gestCli = gestCli;
       this.venta = venta;
       this.ven = ven;
       this.conf = conf;
       this.confPerf = confPerf;
       this.confUsu = confUsu;
       this.usuarios = usuarios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getGest() {
        return this.gest;
    }
    
    public void setGest(Boolean gest) {
        this.gest = gest;
    }
    public Boolean getGestProd() {
        return this.gestProd;
    }
    
    public void setGestProd(Boolean gestProd) {
        this.gestProd = gestProd;
    }
    public Boolean getGestPers() {
        return this.gestPers;
    }
    
    public void setGestPers(Boolean gestPers) {
        this.gestPers = gestPers;
    }
    public Boolean getGestCli() {
        return this.gestCli;
    }
    
    public void setGestCli(Boolean gestCli) {
        this.gestCli = gestCli;
    }
    public Boolean getVenta() {
        return this.venta;
    }
    
    public void setVenta(Boolean venta) {
        this.venta = venta;
    }
    public Boolean getVen() {
        return this.ven;
    }
    
    public void setVen(Boolean ven) {
        this.ven = ven;
    }
    public Boolean getConf() {
        return this.conf;
    }
    
    public void setConf(Boolean conf) {
        this.conf = conf;
    }
    public Boolean getConfPerf() {
        return this.confPerf;
    }
    
    public void setConfPerf(Boolean confPerf) {
        this.confPerf = confPerf;
    }
    public Boolean getConfUsu() {
        return this.confUsu;
    }
    
    public void setConfUsu(Boolean confUsu) {
        this.confUsu = confUsu;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


