package Pojo;
// Generated feb 18, 2016 6:40:59 p.m. by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int perId;
     private String perCi;
     private String perNombre;
     private String perApellido;
     private String perDireccion;
     private String perTelefono;
     private String perEmail;
     private Set usuarios = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int perId) {
        this.perId = perId;
    }
    public Personal(int perId, String perCi, String perNombre, String perApellido, String perDireccion, String perTelefono, String perEmail, Set usuarios) {
       this.perId = perId;
       this.perCi = perCi;
       this.perNombre = perNombre;
       this.perApellido = perApellido;
       this.perDireccion = perDireccion;
       this.perTelefono = perTelefono;
       this.perEmail = perEmail;
       this.usuarios = usuarios;
    }
   
    public int getPerId() {
        return this.perId;
    }
    
    public void setPerId(int perId) {
        this.perId = perId;
    }
    public String getPerCi() {
        return this.perCi;
    }
    
    public void setPerCi(String perCi) {
        this.perCi = perCi;
    }
    public String getPerNombre() {
        return this.perNombre;
    }
    
    public void setPerNombre(String perNombre) {
        this.perNombre = perNombre;
    }
    public String getPerApellido() {
        return this.perApellido;
    }
    
    public void setPerApellido(String perApellido) {
        this.perApellido = perApellido;
    }
    public String getPerDireccion() {
        return this.perDireccion;
    }
    
    public void setPerDireccion(String perDireccion) {
        this.perDireccion = perDireccion;
    }
    public String getPerTelefono() {
        return this.perTelefono;
    }
    
    public void setPerTelefono(String perTelefono) {
        this.perTelefono = perTelefono;
    }
    public String getPerEmail() {
        return this.perEmail;
    }
    
    public void setPerEmail(String perEmail) {
        this.perEmail = perEmail;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


