package Pojo;
// Generated feb 18, 2016 6:40:59 p.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tventa generated by hbm2java
 */
public class Tventa  implements java.io.Serializable {


     private Integer idVenta;
     private int idPers;
     private int idClie;
     private BigDecimal precioVentaTotal;
     private Date fechaRegistro;
     private Set tventadetalles = new HashSet(0);

    public Tventa() {
    }

	
    public Tventa(int idPers, int idClie, BigDecimal precioVentaTotal, Date fechaRegistro) {
        this.idPers = idPers;
        this.idClie = idClie;
        this.precioVentaTotal = precioVentaTotal;
        this.fechaRegistro = fechaRegistro;
    }
    public Tventa(int idPers, int idClie, BigDecimal precioVentaTotal, Date fechaRegistro, Set tventadetalles) {
       this.idPers = idPers;
       this.idClie = idClie;
       this.precioVentaTotal = precioVentaTotal;
       this.fechaRegistro = fechaRegistro;
       this.tventadetalles = tventadetalles;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public int getIdPers() {
        return this.idPers;
    }
    
    public void setIdPers(int idPers) {
        this.idPers = idPers;
    }
    public int getIdClie() {
        return this.idClie;
    }
    
    public void setIdClie(int idClie) {
        this.idClie = idClie;
    }
    public BigDecimal getPrecioVentaTotal() {
        return this.precioVentaTotal;
    }
    
    public void setPrecioVentaTotal(BigDecimal precioVentaTotal) {
        this.precioVentaTotal = precioVentaTotal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getTventadetalles() {
        return this.tventadetalles;
    }
    
    public void setTventadetalles(Set tventadetalles) {
        this.tventadetalles = tventadetalles;
    }




}


